server:
  port: 8035


spring:
  profiles:
    active: dev
  application:
    name: EmployeeManagementService

payroll:
  service:
    base:
      url: http://dummy.restapiexample.com
    endpoint:
      create: /api/v1/create
      getAll: /api/v1/employees

management:
  server:
    port: 8036
  endpoints:
    web:
      exposure:
        include: '*'


